language: cpp
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
      - g++-multilib

before_script:
  - mkdir build && cd build
  - cmake ..

script:
  - make
  - cd ..

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: "test/plugins/samp-graceful-exit.so"
  skip_cleanup: true
  on:
    tags: true
